Homework3
OtusTeam/Clojure-Developer pull request #17
Opened 2023-05-21 12:51 UTC by MitrickX

1) Scramblies - done
2) Magic Square - done
3) Crossword Puzzle - work in progress

2023-05-22 04:39 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (first (filter (complement nil?) args)))
Пока что вижу ровно одно использование этой функции и ровно с двумя аргументами. При этом работает функция как существующий макрос `or`:
```clojure
user=> (or nil 0)
0
user=> (or 42 0)
42
```
Да и в целом вы ниже делаете `(coalesce (get-in ..) 0)`, но ведь `get-in` может возвращать значение по умолчанию, так что может вернуть тот самый `0` без посторонней помощи.

2023-05-22 04:40 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +(defn filled? [board x y] (> (cell board x y) 0))
Для этого есть отдельный предикат `pos?` :)

2023-05-22 04:44 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +        y' (rem (+ y -1 n) n)]
Модульную арифметику обычно делают с помощью `mod`, а не `rem`. Да и работают они по разному:
```clojureuser=> (mod -1 3)
2
user=> (rem -1 3)
-1
```
И именно из-за этой разницы вами приходится `n` добавлять дополнительно, чтобы не уйти "в минус". А вот `mod` работает правильно и при уходе в отрицательные значения координат.

2023-05-22 04:48 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +      (down-move board x y))))
Обычно, если в условной конуструкции с обеими ветками (then+else) в условии имеется not, то стоит подумать об убирании `not` и перемене веток местами. Это так называемое избавление от "negative logic" (можно про это почитать, например, [тут](https://www.obsidiansecurity.com/blog/why-to-stop-writing-negative-code/))

2023-05-22 04:50 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +    (if (> value (* n n))
`(* n n)` вычисляется на каждой итерации. Лучше вынести в let за пределами цикла, а заодно и назвать как-то полезно для читаемости — `max-value`, скажем.

2023-05-22 04:52 UTC, astynax commented on otus-04/src/otus_04/homework/scramblies.clj
> +    (every? (partial contains? letters-set) word)))
А точно код проходит все тесты? Сделайте rebase, если у вас три тест кейса: я в какой-то момент добавил ещё один, который этот код не пройдёт.

2023-05-22 04:53 UTC, astynax commented
Настройте, пожалйста, ваш редактор, чтобы он принудительно сохранял перенос строки в конце файла.

2023-05-22 05:16 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (first (filter (complement nil?) args)))
Логическое ИЛИ тут не сработает - потому что 0 это falsey - тут строго на nil должно проверяться, а мне нужно именно не nil

Про get-in посмотрю и если это будет то, что мне надо - уберу coalesce

2023-05-22 05:17 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +(defn filled? [board x y] (> (cell board x y) 0))
Ок, поправлю позже

2023-05-22 05:17 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +        y' (rem (+ y -1 n) n)]
Ок, перепроверю и поправлю позже

2023-05-22 05:17 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +      (down-move board x y))))
Ок, поправлю позже

2023-05-22 05:17 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +    (if (> value (* n n))
Ок, поправлю позже

2023-05-22 05:20 UTC, MitrickX commented on otus-04/src/otus_04/homework/scramblies.clj
> +    (every? (partial contains? letters-set) word)))
Да, вижу новый тест - попозже прийду с исправлением

2023-05-22 05:36 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (first (filter (complement nil?) args)))
А вот и нет, 0 не ложный в Clojure! Только nil и false ложные.
```clojure
user=> (boolean nil)
false
user=> (boolean 0)
true
```
Но `or` в любом случае не смотрит на последний аргумент, а просто его возвращает, если все предыдущие были истинны:
```clojure
user=> (or nil)
nil
user=> (or false)
false
```
Именно поэтому `or` можно использовать для возврата значения по умолчанию — любого значения, в том числе и ложного, и это будет именно возврат значения, а приведение оного к булеву типу.

2023-05-22 07:12 UTC, MitrickX commented on otus-04/src/otus_04/homework/scramblies.clj
> +    (every? (partial contains? letters-set) word)))
Исправлено

2023-05-22 07:23 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (first (filter (complement nil?) args)))
Ок, понял про or, default убрал в get-in

2023-05-22 07:23 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +(defn filled? [board x y] (> (cell board x y) 0))
Поправил

2023-05-22 07:23 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +        y' (rem (+ y -1 n) n)]
Поправил

2023-05-22 08:28 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (update-in board [y x] (constantly v)))
Почему не `assoc-in`, раз вы всё равно просто заменить значение хотите, а не обновить?

2023-05-22 08:28 UTC, astynax commented on otus-04/src/otus_04/homework/magic_square.clj
> +        y' (mod (+ y -1) n)]
Теперь уже можно на `inc` и `dec` заменить :)

2023-05-22 08:35 UTC, astynax commented on otus-04/src/otus_04/homework/scramblies.clj
> +    word))
Функции выглядят очень похоже. Может быть обобщить?
```clojure
(defn collect-stats [step initial-stats elems]
  (reduce
    (fn [stat key]
      (let [value (get stat key 0)]
        (assoc stat key (step value))))
    initial-stats
    elems))
    
(def count-letters (partial collect-stats inc {})
(def subtract-letters (partial collect-stats dec))
```

2023-05-22 08:51 UTC, MitrickX commented on otus-04/src/otus_04/homework/scramblies.clj
> +    word))
Ну, полностью-то не надо было подсказывать - я просто взял ваш код и вставил :)

2023-05-22 08:51 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +        y' (mod (+ y -1) n)]
done

2023-05-22 08:52 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (update-in board [y x] (constantly v)))
Вот я не нашел ее тогда - пришлось через update-in делать и очень НЕ понравилось
Спасибо за наводку

2023-05-22 08:52 UTC, MitrickX commented on otus-04/src/otus_04/homework/magic_square.clj
> +  (update-in board [y x] (constantly v)))
done

2023-05-29 05:50 UTC, astynax requested changes

2023-05-29 06:51 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Не очень понял как тут map применить - мне на каждый шаг нужно поставлять обновленную борду ? Наверное имелось в виду reduce

2023-05-29 06:56 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Тут наверное даже и map и reduce потому что мне надо скелить (ассоциировать) каждую букву с конкретным номером строки

Так или иначе как раз-таки loop-recur выглядит максимально подходяще, вместо странных приседаний все делается явно, я не через высокоуровневые костыли map reduce. Я бы на проде именно так и делал. Ну ладно так как это учебный пример сделаю вначале сшитие в пары через map а потом reduce для свертки

2023-05-29 07:27 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Ну ладно - вроде неплохо получилось с map + reduce

2023-05-29 07:59 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +            (recur (inc row))))))))
Сделал через map + filter + first

2023-05-29 07:59 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +(defn str-board
Пофиксил

2023-05-29 07:59 UTC, MitrickX commented on otus-04/src/otus_04/homework/scramblies.clj
> +
Поправил

2023-05-29 10:02 UTC, astynax commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Вам нужно в конечном итоге получить новый вектор из старого. Для этого не обязательно делать assoc по букве за раз, а можно сделать `mapv`.

2023-05-29 13:55 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Во-первых, вектор вертикальный 
Во-вторых, вектор, который нужно переписать в матрице, он ведь внутри матрицы как отрезок - не [0; n-1], а там например [2; 5]

Собственно я щас и иду строго вдоль вертикального отрезка-вектора начиная с нужного начала до нужного конца располагая в него мою строку

Не понимаю, какой вариант решения вы мне предлагаете) Если покажите - будет здорово, нет - ну останавливаюсь на последнем map-reduce варианте тогда

2023-05-29 15:21 UTC, astynax commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Показываю:

```clojure
(defn patch-with [v f patch offset]
  (let [row (concat (repeat offset nil)
                    patch
                    (repeat (- (count v) (count patch) offset) nil))]
    (mapv (fn [x p] (if (nil? p) x (f x p)))
          v row)))

;; (patch-with [1 2 3 4 5] + [10 10] 1)
;; => [1 12 13 4 5]

(defn insert-h [field word dx dy]
  (update field dy patch-with (fn [_ p] p) word dx))

;; (insert-h [[0 0 0] [0 0 0] [0 0 0]] [1 2] 1 1)
;; => [[0 0 0] [0 1 2] [0 0 0]]

(defn insert-v [field word dx dy]
  (patch-with field (fn [row p] (assoc row dx p)) word dy))

;; (insert-v [[0 0 0] [0 0 0] [0 0 0]] [1 2] 1 1)
;; => [[0 0 0] [0 1 0] [0 2 0]]
```
А всего-то и нужно уметь применить `[10 10]` к `[1 2 3 4 5]` со сдвигом. Для этого "патч" нужно превратить в `(nil 10 10 nil nil)`, то есть подогнать под длину. Всё, дальше `patch-with` работает и для вертикалей, и для горизонталей, поскольку векторы векторов — векторы сами по себе. И будет этот хелпер работать хоть в трёхмерном пространстве, хоть в семимерном :)

2023-05-29 16:05 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +      false)))
Спасибо, поправил

2023-05-29 16:05 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +   nil))
Обобщил + использовал when

2023-05-29 16:06 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +  (let [{row :row col :col ok? :ok?} (find-free-cell board)]
Да, меня самого бесило, я просто не вспомнил про :keys деструктор :)  Спасибо

2023-05-29 16:06 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          (let [{line :line type :type row :row col :col} blank-line-result
Спасибо, поправил

2023-05-29 16:07 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +         col :col} next-move-state]
Поправил, спасибо

2023-05-29 16:07 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +           rest-matches (rest matches)
Спасибо, поправил

2023-05-29 18:47 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Ладно, спасибо, за хитрый трюк - никогда бы не догадался бы до него сам по себе

2023-05-29 18:47 UTC, MitrickX commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +          chars)))))
Внедрил в код

2023-05-30 04:49 UTC, astynax approved these changes
LGTM

2023-05-30 04:50 UTC, astynax commented
Ставлю "зачёт"!

2023-05-30 04:50 UTC, closed without merging