finish 5th hw
OtusTeam/Clojure-Developer pull request #28
Opened 2023-05-31 17:08 UTC by bondiano

2023-06-07 11:22 UTC, XOMAv2 requested changes
Добрый день, Василий!
У вас отлично получилось реализовать структуру тестов, а именно использовать все возможности библиотеки `clojure.test` и вынести общие функции в пространство имён `test-util`.
Спасибо за выполненную работу.
Я оставил несколько комментариев, в которых даю рекомендации по доработке кода.
Мне показалось особенно удачным точечное использование библиотеки `clojure.test.check`.
Жду исправлений и хорошего дня

2023-06-07 11:22 UTC, XOMAv2 commented on url-shortener/test/url_shortener/test_util.clj
> +(defn ^:export assert-output [expected f]
Непонятна цель существования этой функции.
1) Она производит сайд эффект в результате вызова `is`, что не очень хорошо.
2) Она скрывает от читателя тот факт, что вызывается `is`, я не сразу обратил внимание, что она называется `assert-` и ведёт себя соответствующе.
3) Несколько раз в коде используется вызов `(str/trim (with-out-str ...))`, предлагаю поместить его в отдельную функцию, а не писать кастомную конструкцию для проверки.
4) А вообще нужно ли использовать `with-out-str`? Можно ли переписать функции `shorten-url` и `find-long-url`, чтобы результатом их работы были строки без сайд эффектов, а уже потребители результатов этих функций его печатали?

2023-06-07 11:22 UTC, XOMAv2 commented on url-shortener/test/url_shortener/core_test.clj
> +   (tc/quick-check 10
Применение `clojure.test.check` выглядит уместно и изящно, классно!

2023-06-07 12:02 UTC, bondiano commented on url-shortener/test/url_shortener/test_util.clj
> +(defn ^:export fix-with-url-db
осталось после экспеременов, спасибо, убрал!

2023-06-07 12:06 UTC, XOMAv2 reviewed
Уточнил задание, модифицировать исходный код нельзя, поэтому придётся тестировать функции с сайд эффектами.

2023-06-07 12:54 UTC, bondiano commented
Спасибо, поправил!

2023-06-08 13:32 UTC, XOMAv2 requested changes
Добрый день, Василий.
Код аккуратный, элегантно переписал фикстуру `fix-with-url-db`.
Предлагаю внести правки и можно заливать.
Спасибо за работу

2023-06-08 17:33 UTC, bondiano commented
@XOMAv2 поправил!)

2023-06-08 17:57 UTC, XOMAv2 reviewed
Задание принято

2023-06-08 17:58 UTC, closed without merging