Homework5
OtusTeam/Clojure-Developer pull request #30
Opened 2023-06-10 13:00 UTC by MitrickX

Unit tests for url shortener

2023-06-13 14:06 UTC, XOMAv2 requested changes
Добрый день, Дмитрий!

Вижу, что вам удалось разобраться с clojure.test. Спасибо за выполненную работу.

В комментариях я оставил несколько предложений по доработке кода, которые прошу учесть.

Особенно мне понравилось, что функции в core.clj были переписаны так, чтобы они не производили сайд-эффектов и зависели только от своих аргументов. С такими функциями легче работать и их легче тестировать.

Ожидаю правок, хорошего дня)

2023-06-13 15:53 UTC, MitrickX commented on url-shortener/test/url_shortener/core_test.clj
> +    (do-test-on-random-int-inputs 100 #(quot % base-number) (comp int sut/get-idx)))
quot - целочисленное деление
https://clojuredocs.org/clojure.core/quot

2023-06-13 15:56 UTC, MitrickX commented on url-shortener/src/url_shortener/core.clj
> +(defn do-shorten-url [db url]
А там ведь и так сайд эффект - оно там пишет в БД :)

2023-06-13 16:18 UTC, XOMAv2 commented on url-shortener/test/url_shortener/core_test.clj
> +    (do-test-on-random-int-inputs 100 #(quot % base-number) (comp int sut/get-idx)))
Моя ошибка, перепутал с `quote`

2023-06-13 16:20 UTC, XOMAv2 commented on url-shortener/src/url_shortener/core.clj
> +(defn do-shorten-url [db url]
Читает) В данном случае я не настаиваю

2023-06-13 16:39 UTC, MitrickX commented on url-shortener/src/url_shortener/core.clj
> +(defn do-shorten-url [db url]
И читает и пишет (там есть spit ведь)

Так или иначе я переименовал - переименовывать не сложно :)

2023-06-14 09:48 UTC, MitrickX commented on url-shortener/test/url_shortener/core_test.clj
> +    (do-test-on-random-int-inputs 100 #(get symbols (rem % base-number)) sut/get-symbol-by-idx))
Добавил доп тесты - с диапазонами (типа для покрытия всех классов эквивалентности) + чуть-чуть фиксированные

2023-06-14 09:49 UTC, MitrickX commented on url-shortener/test/url_shortener/core_test.clj
> +    (let [db (io/as-file "test-short-url-and-back.txt")]
Добавил фикстуру, которая подчищает за собой

2023-06-15 09:05 UTC, MitrickX commented on url-shortener/test/url_shortener/core_test.clj
> +(defn do-test-on-random-int-inputs
Вынес

2023-06-15 10:32 UTC, XOMAv2 requested changes
Предлагаю доработать фикстуру `fix-with-tmp-file` и можно закрывать

2023-06-15 10:32 UTC, XOMAv2 commented on url-shortener/test/url_shortener/core_test.clj
> +(defn fix-with-tmp-file [t]
Лучше поместить её в `test-util` для переиспользования.

Предлагаю переписать таким образом, чтобы она создавала файл с указанным именем и байндила его к указанному вару.

```clojure
(defn fix-with-tmp-file
  [filevar filename]
  (fn [t]
    (let [file (java.io.File/createTempFile filename nil)]
      (with-bindings {filevar file}
        (t)
        (clojure.java.io/delete-file file)))))

(def ^:dynamic *test-db*)
(def test-db-file-name "test-short-url-and-back.txt")

(use-fixtures :each
  (tu/fix-with-tmp-file #'*test-db* test-db-file-name))
```

2023-06-15 10:32 UTC, XOMAv2 commented on url-shortener/.gitignore
> +test-short-url-and-back.txt
Эту строчку можно удалить

2023-06-15 10:32 UTC, XOMAv2 commented on url-shortener/src/url_shortener/core.clj
> +(defn get-find-long-url [db url]
`get-long-url`

2023-06-15 10:32 UTC, XOMAv2 commented on url-shortener/test/url_shortener/core_test.clj
> +    (let [db (io/as-file "test-short-url-and-back.txt")]
После модификации фикстуры можно будет записать так `(let [db *test-db*])`

2023-06-15 14:22 UTC, MitrickX commented on url-shortener/test/url_shortener/core_test.clj
> +(defn fix-with-tmp-file [t]
А зачем `:each` - на каждый тест ведь будет создаваться temp файл и удалятся - а нужен только для одного теста :) Кажется `:once` тут более подходящий вариант

2023-06-15 14:56 UTC, XOMAv2 commented on url-shortener/test/url_shortener/core_test.clj
> +(defn fix-with-tmp-file [t]
В данном случае подходит и `:once`

2023-06-15 14:57 UTC, XOMAv2 commented on url-shortener/src/url_shortener/core.clj
> +(defn do-shorten-url [db url]
Почему-то смотрел в `long-url`

2023-06-15 14:57 UTC, closed without merging